name: Kubernetes
title: Kubernetes
description: Production-Grade Container Orchestration
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      version: "v1.5.1"
      githubbranch: "master"
      docsbranch: "master"
  -
    scope:
      path: "docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# SEO
logo: /images/favicon.png
twitter:
  username: kubernetesio

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - guides
  - tutorials
  - tasks
  - concepts
  - reference
  - tools
  - samples
  - support

collections:
  thtest-v1.4:
    output: true
    permalink: /th/v1.4/:path
  thtest-v1.3:
    output: true
    permalink: /th/v1.3/:path
  thtest-v1.2:
    output: true
    permalink: /th/v1.2/:path
